### ISSUE TITLE
Wrong link to documentation 

### ISSUE THREAD

**Issue by kavalerov** [ably-labs/ably-datadog-lambda#1]
> Set the S3 bucket, Datadog API key, and Ably External ID parameters in cloudformation/parameters.json (see [here](https://knowledge.ably.com/authentication-for-reactor-rules-for-aws-reactor-events-for-lambda-functions-reactor-firehose-for-aws-sqs-and-kinesis) for instructions on how to determine your Ably External ID, which takes the form <accountID>.<appID>)

The link used in this sentence in the readme doesn't actually lead to a page that shows how to determine Ably External ID (or I am missing something very obvious there...). Actually, the only place where I could find information on how to find account ID is in the Control API docs: https://ably.com/documentation/control-api#account-id. I have created a [docs issue](https://github.com/ably/docs/issues/1191) to add a separate topic, but in the meantime we should probably change the link to the existing page.

**Comment by lmars** [comment]
Good point, the docs were pretty lacking on this one 👍
